# Generated by Django 4.0.3 on 2022-03-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='Especialidad',
            new_name='especialidad',
        ),
    ]
