# Generated by Django 4.0.3 on 2022-03-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0002_rename_especialidad_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
