# Generated by Django 4.0.3 on 2022-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0004_alter_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
