# Generated by Django 4.0.3 on 2022-03-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0005_alter_paciente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='dni',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
