# Generated by Django 4.0.3 on 2022-03-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0006_medico_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='dni',
        ),
    ]
