# Generated by Django 4.0.3 on 2022-03-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0007_remove_medico_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='dni',
            field=models.IntegerField(default=123123123, unique=True),
            preserve_default=False,
        ),
    ]
