# Generated by Django 4.0.3 on 2022-03-30 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0008_medico_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='dni',
            new_name='matricula',
        ),
    ]
